#!/usr/bin/env python3
"""
Extract LaTeX floats (figure/table, starred and unstarred) from a .tex file
in order of appearance, write them to an output .tex file, and comment out
their original positions in-place in the input file.

Reversible approach:
- Original blocks are preserved (commented out) in the source file.
- Extracted blocks are written verbatim to the output file.
"""

from __future__ import annotations
import argparse
import datetime as _dt
import os
import re
import shutil
from dataclasses import dataclass
from typing import List, Tuple, Optional

FLOAT_ENVS = (
    "figure", "figure*",
    "table", "table*",
    "sidewaysfigure", "sidewaystable","ThreePartTable",
)

# Build a regex that matches any env in FLOAT_ENVS (and escapes * properly)
ENV_ALT = "|".join(re.escape(e) for e in FLOAT_ENVS)

BEGIN_RE = re.compile(
    rf"^[ \t]*\\begin\{{({ENV_ALT})\}}.*$",
    re.MULTILINE
)


def _now_stamp() -> str:
    return _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


@dataclass
class Block:
    env: str
    start: int  # char index in full text
    end: int  # char index (end exclusive)
    start_line: int  # 1-based
    end_line: int  # 1-based
    text: str


def _index_to_line(text: str, idx: int) -> int:
    # 1-based line number for char index idx
    return text.count("\n", 0, idx) + 1


def _find_matching_end(text: str, env: str, begin_pos: int) -> int:
    """
    Find the end index (end-exclusive) of the matching \\end{env} for the \\begin{env}
    that starts at begin_pos. Assumes floats are not nested within same env type.
    """
    # We search from begin_pos onward for the exact end line
    end_pat = re.compile(rf"^[ \t]*\\end\{{{re.escape(env)}\}}[ \t]*.*$",
                         re.MULTILINE)
    m = end_pat.search(text, begin_pos)
    if not m:
        raise ValueError(f"Could not find matching \\end{{{env}}} after position {begin_pos}")
    # Include through the end of that line
    line_end = text.find("\n", m.end())
    if line_end == -1:
        return len(text)
    return line_end + 1


def extract_blocks(tex: str) -> List[Block]:
    blocks: List[Block] = []
    for m in BEGIN_RE.finditer(tex):
        env = m.group(1)
        start = m.start()
        end = _find_matching_end(tex, env, m.end())
        blk_text = tex[start:end]
        blocks.append(
            Block(
                env=env,
                start=start,
                end=end,
                start_line=_index_to_line(tex, start),
                end_line=_index_to_line(tex, end),
                text=blk_text
            )
        )
    # Ensure sorted by appearance
    blocks.sort(key=lambda b: b.start)
    return blocks


def comment_out_block(block_text: str, tag: str) -> str:
    """
    Comment out a block line-by-line. Add clear BEGIN/END tags.
    """
    lines = block_text.splitlines(True)  # keep line endings
    commented = []
    commented.append(f"% >>> MOVED_FLOAT_BEGIN {tag}\n")
    for ln in lines:
        # Avoid double-commenting if already commented fully
        if ln.lstrip().startswith("%"):
            commented.append("% " + ln)  # still comment it, but keep visible
        else:
            commented.append("% " + ln)
    if not commented[-1].endswith("\n"):
        commented[-1] += "\n"
    commented.append(f"% <<< MOVED_FLOAT_END {tag}\n")
    return "".join(commented)


def write_extracted(blocks: List[Block], out_path: str, src_path: str) -> None:
    header = [
        "% Auto-generated by extract_floats.py\n",
        f"% Source: {src_path}\n",
        f"% Generated: {_now_stamp()}\n",
        "%\n",
        "% Paste/\\input{} this file where you want the floats to appear.\n",
        "% The floats below are in the order they appeared in the source.\n",
        "%\n\n",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.writelines(header)
        for i, b in enumerate(blocks, start=1):
            tag = f"{i:04d}:{b.env}:L{b.start_line}-L{b.end_line}"
            f.write(f"% === FLOAT {tag} ===\n")
            f.write(b.text)
            if not b.text.endswith("\n"):
                f.write("\n")
            f.write("\n")


def apply_inplace(tex: str, blocks: List[Block], dry_run: bool) -> str:
    """
    Replace each block with a commented version + a short marker.
    Work from end -> start so indices stay valid.
    """
    new_tex = tex
    for i, b in enumerate(sorted(blocks, key=lambda x: x.start, reverse=True), start=1):
        # tag based on reverse index isn't great; compute forward index via original list
        # We'll locate forward index by identity:
        fwd_i = blocks.index(b) + 1
        tag = f"{fwd_i:04d}:{b.env}:L{b.start_line}-L{b.end_line}"
        replacement = (
                f"% [MOVED FLOAT {tag}] "
                f"(see extracted file)\n"
                + comment_out_block(b.text, tag)
        )
        new_tex = new_tex[:b.start] + replacement + new_tex[b.end:]
    return new_tex


def main():
    ap = argparse.ArgumentParser(
        description="Extract LaTeX figure/table floats to a file and comment them out in place.")
    ap.add_argument("tex_file", help="Path to the main .tex file to process")
    ap.add_argument("-o", "--out", default="extracted_floats.tex", help="Output .tex file for extracted floats")
    ap.add_argument("--backup", action="store_true", help="Create a .bak copy of the input .tex before modifying")
    ap.add_argument("--dry-run", action="store_true", help="Do not write any changes; just report what would happen")
    args = ap.parse_args()

    tex_path = args.tex_file
    out_path = args.out

    with open(tex_path, "r", encoding="utf-8") as f:
        tex = f.read()

    blocks = extract_blocks(tex)
    if not blocks:
        print("No figure/table floats found. Nothing to do.")
        return

    print(f"Found {len(blocks)} float(s):")
    for i, b in enumerate(blocks, start=1):
        print(f"  {i:3d}. {b.env:7s} lines {b.start_line}-{b.end_line}")

    if args.dry_run:
        print("\n--dry-run set: not writing any files.")
        print(f"Would write extracted floats to: {out_path}")
        print(f"Would modify in place: {tex_path} (backup={'yes' if args.backup else 'no'})")
        return

    # Write extracted floats first
    write_extracted(blocks, out_path, tex_path)
    print(f"\nWrote extracted floats to: {out_path}")

    # Backup if requested
    if args.backup:
        bak_path = tex_path + ".bak"
        shutil.copy2(tex_path, bak_path)
        print(f"Backup created: {bak_path}")

    # Apply in-place modifications
    new_tex = apply_inplace(tex, blocks, dry_run=False)
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(new_tex)
    print(f"Modified in place: {tex_path}")
    print("\nNext step: insert this where you want the figures/tables to appear:")
    print(f"  \\clearpage\n  \\input{{{out_path}}}\n")


if __name__ == "__main__":
    main()
